### ISSUE TITLE
Diseñar sistema de puntos y usuarios, ranking para quizes a traves de frames Farcaster

### ISSUE THREAD

**Issue by hsantana** [Blind-Gallery/BG-Academy#251]

**Comment by crissthiandi** [comment]
Avances con sistema de puntaje y captura de datos:
https://github.com/GenArtAggregator/academy-frames/pull/1
https://github.com/GenArtAggregator/academy-frames/pull/2

**Comment by crissthiandi** [comment]
Continuación de avances:
https://github.com/GenArtAggregator/academy-frames/pull/3

**Comment by tlacloc** [comment]
esto va en otro repo
